### ISSUE TITLE
How to Genareate DB?

### ISSUE THREAD

**Issue by robyle** [Gordon-Allen/Activity-Center#1]
When I download code,Just preapare to running,There is Error,just like the picture.
![20191026104322](https://user-images.githubusercontent.com/11662528/67613227-adf72880-f7dd-11e9-8ae4-de0b74a06330.png)

**Comment by Gordon-Allen** [comment]
robyle,

Sorry for my delay in responding! 

To generate your DB (_assuming you are using my MySQL Server and have it installed on your local machine_, here's the link to download it if not [https://dev.mysql.com/downloads/mysql/](url) ), follow these steps to perform a **Code-First DB Generation**:

1) Go into your "**appsettings.json**" file and ensure that all the _connection string_ info _(server, userid, password, port)_ is correct for your local MySQL server D/B. The _"database"_ name can be anything you'd like as it will create itself later in our steps:

![image](https://user-images.githubusercontent.com/28709311/70161813-aeab9600-168a-11ea-8db6-1b6af6e60f46.png)

2) Once have that done, go to your Terminal (Mac) or Command Prompt (Windows), navigate to the _"Activity-Center"_ root directory and run the below command. If it gives you an error, just read thru the error response and see which version of EF Core.MySQL it needs and edit the "_-v x.x.x_" section to that:

`dotnet add package Pomelo.EntityFrameworkCore.MySql -v 2.1.1`

3) Once that successfully installs, run the below two commands in your Terminal/Command Prompt. You may name the migration anything you'd like, I normally call it _"FirstMigration"_:

`dotnet ef migrations add FirstMigration`
`dotnet ef database update`

4) Once the "dotnet ef database update" command comes back successfully, your D/B is created and you should be good-to-go!

Again sorry for my delay in responding and let me know if you have any more errors, my friend!

**Comment by robyle** [comment]
Gordon-Allen,

Thank you so much for your detail answers.   I have sloved that errors.  I‘m tried rebuild an other user manage data system.

**Comment by Gordon-Allen** [comment]
Amazing to hear, robyle! 

Let me know if you have any other questions/errors I can help with!
